(() => {
  'use strict';

  const BAGHDAD = { lat: 33.3152, lng: 44.3661, zoom: 12 };
  const CACHE_KEY = 'rashiq_osm_cache_v1';
  const FAVORITES_KEY = 'rashiq_favorites_v1';
  const CACHE_TTL = 6 * 60 * 60 * 1000;
  const REVIEWED_AT = '2026-08-14';

  const SEED_GYMS = [
    {id:'seed-f45-mansour',name:'F45 Training Mansour Central',nameAr:'F45 المنصور',lat:33.3170625,lng:44.3520625,area:'المنصور',address:'شارع سلمان فائق، المنصور، بغداد',phone:'+9647722664545',type:'functional',women:false,alwaysOpen:false,hours:'عادةً 07:00–22:00 (تحقق قبل الزيارة)',rating:4.8,reviews:14,verified:true,reviewedAt:REVIEWED_AT,source:'official+directory',tags:['F45','functional','HIIT','كروس فت','المنصور']},
    {id:'seed-nitro-yarmouk',name:'Nitro Gym',nameAr:'نايترو جيم',lat:33.3035203,lng:44.3458022,area:'اليرموك',address:'شارع برج بغداد، اليرموك، بغداد',phone:'+9647722264888',type:'classic',women:false,alwaysOpen:false,hours:'08:00–01:00',rating:4.5,reviews:null,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['weights','bodybuilding','أوزان','اليرموك']},
    {id:'seed-black-mansour',name:'Black Gym Almansour',nameAr:'بلاك جيم المنصور',lat:33.316044,lng:44.3531082,area:'المنصور',address:'مدخل شارع الأميرات، المنصور، بغداد',phone:'+9647728000345',type:'classic',women:false,alwaysOpen:false,hours:'06:00–01:00 تقريبًا؛ الجمعة يبدأ لاحقًا',rating:4.4,reviews:null,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['weights','bodybuilding','أوزان','المنصور']},
    {id:'seed-plaza-women',name:'Plaza Women Gym',nameAr:'بلازا وومن جيم',lat:33.3185856,lng:44.3547581,area:'المنصور',address:'المنصور، بغداد',phone:'+9647722707011',type:'classic',women:true,alwaysOpen:false,hours:'تحقق من الجيم قبل الزيارة',rating:3.5,reviews:6,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['women','ladies','نسائي','نساء','المنصور']},
    {id:'seed-titans',name:'Titans Gym',nameAr:'تايتنز جيم',lat:33.2913125,lng:44.3526875,area:'جنوب المنصور',address:'Jinub Street، بغداد',phone:'+9647714044221',type:'classic',women:false,alwaysOpen:false,hours:'09:00–02:00 غالبًا؛ الجمعة أقصر',rating:4.5,reviews:133,verified:true,reviewedAt:REVIEWED_AT,source:'directory',amenities:['ساونا'],tags:['weights','bodybuilding','ساونا']},
    {id:'seed-legend',name:'Legend Hall Bodybuilding & Fitness',nameAr:'ليجند هول',lat:33.3209375,lng:44.3953125,area:'وسط بغداد',address:'89CW+94X، بغداد',phone:'+9647702914636',type:'classic',women:false,alwaysOpen:false,hours:'تحقق من الجيم قبل الزيارة',rating:3.3,reviews:17,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['bodybuilding','fitness','كمال اجسام']},
    {id:'seed-baghdad-sport-center',name:'Baghdad Sport Center',nameAr:'مركز بغداد الرياضي',lat:33.3096875,lng:44.4344375,area:'الكرادة / شرق بغداد',address:'8C5M+VQ9، بغداد',phone:'+9647712830122',type:'sports',women:false,alwaysOpen:false,hours:'08:00–22:00',rating:4.4,reviews:49,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['sports','fitness','مركز رياضي']},
    {id:'seed-iraq-fitness',name:'Iraq Fitness Bodybuilding & Fitness',nameAr:'عراق فتنس',lat:33.3233125,lng:44.4925625,area:'شرق بغداد',address:'8FFV+825، بغداد',phone:'',type:'classic',women:false,alwaysOpen:false,hours:'06:00–01:00',rating:3.9,reviews:100,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['bodybuilding','fitness','كمال اجسام']},
    {id:'seed-gaith',name:'Gaith Gym',nameAr:'غيث جيم',lat:33.3486875,lng:44.4134375,area:'شارع فلسطين',address:'8CX7+F9F، بغداد',phone:'',type:'classic',women:false,alwaysOpen:false,hours:'تحقق من الجيم قبل الزيارة',rating:2.9,reviews:8,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['شارع فلسطين','weights']},
    {id:'seed-titanium-2',name:'Titanium GYM II',nameAr:'تايتانيوم جيم 2',lat:33.3615625,lng:44.4090625,area:'شارع فلسطين',address:'9C65+JJ7، شارع فلسطين، بغداد',phone:'',type:'classic',women:false,alwaysOpen:false,hours:'تحقق من الجيم قبل الزيارة',rating:null,reviews:null,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['شارع فلسطين','weights']},
    {id:'seed-adhamiya',name:'Adhamiya GYM',nameAr:'جيم الأعظمية',lat:33.3694375,lng:44.3700625,area:'الأعظمية',address:'999C+Q2V، الأعظمية، بغداد',phone:'',type:'classic',women:false,alwaysOpen:false,hours:'تحقق من الجيم قبل الزيارة',rating:null,reviews:null,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['الأعظمية','weights']},
    {id:'seed-baghdad-gym',name:'Baghdad Gym',nameAr:'بغداد جيم',lat:33.2420625,lng:44.2981875,area:'جنوب غرب بغداد',address:'67RX+R7، بغداد',phone:'',type:'classic',women:false,alwaysOpen:false,hours:'10:00–00:00؛ الجمعة من 16:00 تقريبًا',rating:4.1,reviews:30,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['weights','bodybuilding']},
    {id:'seed-jadriya-padel',name:'Al Jadriya Padel',nameAr:'الجادرية بادل',lat:33.2714375,lng:44.3865625,area:'الجادرية',address:'79CP+HJ، الجادرية، بغداد',phone:'+9647750604060',type:'sports',women:false,alwaysOpen:true,hours:'24/7 بحسب الدليل',rating:null,reviews:null,verified:true,reviewedAt:REVIEWED_AT,source:'directory',tags:['padel','sports','بادل','الجادرية']},
    {id:'seed-fit20-mansour',name:'fit20 Baghdad Mansour',nameAr:'fit20 المنصور',lat:33.3126875,lng:44.3524375,area:'المنصور',address:'شارع الأميرات، مبنى FastPay، بغداد',phone:'+9647751108000',type:'studio',women:false,alwaysOpen:false,hours:'بموعد؛ تحقق قبل الزيارة',rating:null,reviews:null,verified:true,approximate:true,reviewedAt:REVIEWED_AT,source:'official',tags:['fit20','studio','personal training','المنصور']},
    {id:'seed-fit20-zayona',name:'fit20 Baghdad Zayona',nameAr:'fit20 زيونة',lat:33.3320625,lng:44.4526875,area:'زيونة',address:'قرب زيونة مول، بغداد',phone:'+9647714408111',type:'studio',women:false,alwaysOpen:false,hours:'09:00–22:00؛ غالبًا بموعد',rating:5.0,reviews:5,verified:true,approximate:true,reviewedAt:REVIEWED_AT,source:'official+directory',tags:['fit20','studio','personal training','زيونة']}
  ];

  const $=id=>document.getElementById(id);
  const els={search:$('searchInput'),clearSearch:$('clearSearch'),refresh:$('refreshBtn'),locate:$('locateBtn'),floatingLocate:$('floatingLocate'),install:$('installBtn'),filters:$('filters'),gymList:$('gymList'),empty:$('emptyState'),reset:$('resetFilters'),gymCount:$('gymCount'),status:$('dataStatus'),coverage:$('coverageLabel'),hint:$('mapHint'),sidebar:$('sidebar'),sheetToggle:$('sheetToggle'),sortRecommended:$('sortRecommended'),sortNearest:$('sortNearest'),detailsModal:$('detailsModal'),detailsContent:$('detailsContent'),aboutModal:$('aboutModal'),toast:$('toast')};
  const state={all:[...SEED_GYMS],visible:[],filter:'all',sort:'recommended',search:'',favorites:new Set(readJSON(FAVORITES_KEY,[])),userLocation:null,selectedId:null,map:null,markers:new Map(),userMarker:null,deferredInstall:null,liveLoaded:false};

  function readJSON(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}}
  function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
  function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function normalizeText(s=''){return String(s).toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').trim()}
  function kmBetween(a,b){const R=6371,d2r=Math.PI/180,dLat=(b.lat-a.lat)*d2r,dLng=(b.lng-a.lng)*d2r;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*d2r)*Math.cos(b.lat*d2r)*Math.sin(dLng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
  function distanceLabel(km){if(!Number.isFinite(km))return'';return km<1?`${Math.max(50,Math.round(km*1000/50)*50)} م`:`${km.toFixed(km<10?1:0)} كم`}
  function typeLabel(type){return({classic:'أوزان ولياقة',functional:'Functional',sports:'مركز رياضي',studio:'ستوديو تدريب'})[type]||'لياقة'}

  function inferArea(lat,lng){const areas=[['المنصور',33.315,44.351],['اليرموك',33.304,44.346],['الحارثية',33.329,44.340],['الجادرية',33.274,44.389],['الكرادة',33.302,44.423],['زيونة',33.329,44.454],['شارع فلسطين',33.347,44.421],['الأعظمية',33.371,44.371],['العامرية',33.292,44.287],['الدورة',33.246,44.396],['الغدير',33.303,44.471],['بغداد الجديدة',33.312,44.489]];let best=null;for(const [name,aLat,aLng] of areas){const d=kmBetween({lat,lng},{lat:aLat,lng:aLng});if(!best||d<best.d)best={name,d}}return best&&best.d<4.5?best.name:'بغداد'}
  function classify(tags,name){const s=normalizeText(`${name} ${Object.values(tags||{}).join(' ')}`);if(/crossfit|cross fit|functional|f45|hiit|كروس|وظيفي/.test(s))return'functional';if(/padel|football|sport centre|sports centre|مركز رياضي|بادل/.test(s))return'sports';if(/studio|personal training|fit20|pilates|yoga|ستوديو|يوغا|بيلاتس/.test(s))return'studio';return'classic'}
  function isWomenOnly(tags,name){const s=normalizeText(`${name} ${(tags&&Object.values(tags).join(' '))||''}`);return/women|woman|ladies|female|نسائي|نساء|سيدات|للسيدات/.test(s)}
  function parsePhone(tags={}){return tags.phone||tags['contact:phone']||tags.mobile||tags['contact:mobile']||''}
  function parseAddress(tags={}){const parts=[tags['addr:street'],tags['addr:suburb'],tags['addr:district'],tags['addr:city']].filter(Boolean);return parts.length?[...new Set(parts)].join('، '):''}

  function normalizeOSM(el){const tags=el.tags||{},lat=el.lat??el.center?.lat,lng=el.lon??el.center?.lon;if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const name=tags['name:ar']||tags.name||tags['name:en']||'مركز لياقة بدون اسم',opening=tags.opening_hours||'';return{id:`osm-${el.type}-${el.id}`,osmId:`${el.type}/${el.id}`,name,nameAr:tags['name:ar']||'',lat,lng,area:tags['addr:suburb']||tags['addr:district']||inferArea(lat,lng),address:parseAddress(tags)||inferArea(lat,lng),phone:parsePhone(tags),type:classify(tags,name),women:isWomenOnly(tags,name),alwaysOpen:/24\s*\/\s*7/i.test(opening),hours:opening||'غير مذكور على الخريطة',rating:null,reviews:null,verified:false,reviewedAt:null,source:'OpenStreetMap',website:tags.website||tags['contact:website']||'',instagram:tags.instagram||tags['contact:instagram']||'',tags:Object.values(tags).filter(v=>typeof v==='string').slice(0,20)}}
  function similarName(a,b){const A=normalizeText(a).replace(/\b(gym|fitness|club|hall|جيم|فتنس|نادي|قاعة)\b/g,'').trim(),B=normalizeText(b).replace(/\b(gym|fitness|club|hall|جيم|فتنس|نادي|قاعة)\b/g,'').trim();if(!A||!B)return false;return A===B||A.includes(B)||B.includes(A)}
  function mergeData(osmGyms){const merged=SEED_GYMS.map(x=>({...x}));for(const g of osmGyms){let duplicateIndex=-1;for(let i=0;i<merged.length;i++){const d=kmBetween(g,merged[i]);if((d<0.02&&similarName(g.name,merged[i].name))||(d<0.25&&similarName(g.name,merged[i].name))){duplicateIndex=i;break}}if(duplicateIndex>=0){const s=merged[duplicateIndex];merged[duplicateIndex]={...g,...s,phone:s.phone||g.phone,hours:s.hours||g.hours,address:s.address||g.address,area:s.area||g.area,website:s.website||g.website,instagram:s.instagram||g.instagram,osmId:g.osmId,osmLinked:true}}else merged.push(g)}return merged}

  function setStatus(kind,text){els.status.classList.toggle('loading',kind==='loading');els.status.classList.toggle('offline',kind==='offline');els.status.innerHTML=`<i></i> ${esc(text)}`}
  function initMap(){state.map=L.map('map',{zoomControl:false,preferCanvas:true,minZoom:10,maxZoom:19}).setView([BAGHDAD.lat,BAGHDAD.lng],BAGHDAD.zoom);L.control.zoom({position:'bottomleft'}).addTo(state.map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);state.map.on('moveend',()=>{const c=state.map.getCenter();els.hint.textContent=`وسط الخريطة: ${c.lat.toFixed(3)}, ${c.lng.toFixed(3)}`})}
  function markerIcon(g,selected=false){return L.divIcon({className:'',html:`<div class="gym-pin ${g.verified?'verified':'osm'} ${selected?'active':''}"><div class="gym-pin-core"><span></span></div></div>`,iconSize:[34,42],iconAnchor:[17,38],popupAnchor:[0,-34]})}
  function popupHTML(g){return`<div class="popup"><h4>${esc(g.nameAr||g.name)}</h4><p>${esc(g.area)} · ${esc(typeLabel(g.type))}</p><button class="popup-btn" data-popup-id="${esc(g.id)}">التفاصيل</button></div>`}
  function syncMarkers(list){const visibleIds=new Set(list.map(g=>g.id));for(const[id,m]of state.markers){if(!visibleIds.has(id)){state.map.removeLayer(m);state.markers.delete(id)}}for(const g of list){let m=state.markers.get(g.id);if(!m){m=L.marker([g.lat,g.lng],{icon:markerIcon(g,state.selectedId===g.id),keyboard:true}).bindPopup(popupHTML(g),{closeButton:false,offset:[0,-4]}).on('click',()=>selectGym(g.id,false)).addTo(state.map);m.on('popupopen',e=>{const btn=e.popup.getElement()?.querySelector('[data-popup-id]');if(btn)btn.onclick=()=>openDetails(g.id)});state.markers.set(g.id,m)}else{m.setLatLng([g.lat,g.lng]);m.setIcon(markerIcon(g,state.selectedId===g.id))}}}

  function scoreGym(g){let s=0;if(g.verified)s+=50;if(g.rating)s+=Math.max(0,g.rating-3)*8;if(g.reviews)s+=Math.min(14,Math.log10(g.reviews+1)*6);if(g.phone)s+=4;if(g.hours&&!/غير مذكور|تحقق/.test(g.hours))s+=3;if(g.approximate)s-=4;return s}
  function currentVisible(){const q=normalizeText(state.search);let list=state.all.filter(g=>{if(state.filter==='classic'&&g.type!=='classic')return false;if(state.filter==='functional'&&g.type!=='functional')return false;if(state.filter==='women'&&!g.women)return false;if(state.filter==='247'&&!g.alwaysOpen)return false;if(state.filter==='saved'&&!state.favorites.has(g.id))return false;if(q){const hay=normalizeText([g.name,g.nameAr,g.area,g.address,...(g.tags||[])].join(' '));if(!hay.includes(q))return false}return true});for(const g of list)g._distance=state.userLocation?kmBetween(state.userLocation,g):null;if(state.sort==='nearest'&&state.userLocation)list.sort((a,b)=>(a._distance??999)-(b._distance??999));else list.sort((a,b)=>scoreGym(b)-scoreGym(a)||(a.nameAr||a.name).localeCompare(b.nameAr||b.name,'ar'));return list}
  function cardHTML(g){const saved=state.favorites.has(g.id),title=g.nameAr||g.name,subtitle=g.nameAr&&g.nameAr!==g.name?g.name:typeLabel(g.type);return`<article class="gym-card ${state.selectedId===g.id?'selected':''}" data-id="${esc(g.id)}" tabindex="0"><div class="card-top"><div class="card-title"><h3>${esc(title)}</h3><p>${esc(subtitle)}</p></div><button class="save-btn ${saved?'saved':''}" data-save="${esc(g.id)}" aria-label="${saved?'إزالة من المحفوظة':'حفظ الجيم'}"><svg viewBox="0 0 24 24"><path d="M6 3h12v18l-6-4-6 4V3Z" fill="${saved?'currentColor':'none'}" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg></button></div><div class="card-meta"><span class="badge">${esc(g.area)}</span><span class="badge">${esc(typeLabel(g.type))}</span>${g.women?'<span class="badge women">للنساء</span>':''}${g.alwaysOpen?'<span class="badge">24/7</span>':''}${g.verified?'<span class="badge verified">متحقق</span>':'<span class="badge osm">OSM</span>'}</div><div class="card-actions"><div>${g.rating?`<span class="rating">★ ${g.rating.toFixed(1)}${g.reviews?` <small>(${g.reviews})</small>`:''}</span>`:'<span class="rating">بيانات مفتوحة</span>'}</div><div class="distance">${g._distance!=null?esc(distanceLabel(g._distance)):(g.phone?'اتصال متاح':'')}</div><button class="directions" data-directions="${esc(g.id)}">الاتجاهات</button></div></article>`}
  function render({fitMap=false}={}){state.visible=currentVisible();els.gymCount.textContent=`${state.visible.length} جيم`;els.gymList.innerHTML=state.visible.map(cardHTML).join('');els.empty.hidden=state.visible.length!==0;syncMarkers(state.visible);if(fitMap&&state.visible.length){const bounds=L.latLngBounds(state.visible.map(g=>[g.lat,g.lng]));state.map.fitBounds(bounds.pad(.12),{maxZoom:14,animate:true})}}
  function selectGym(id,pan=true){state.selectedId=id;const g=state.all.find(x=>x.id===id);for(const[mid,m]of state.markers){const mg=state.all.find(x=>x.id===mid);if(mg)m.setIcon(markerIcon(mg,mid===id))}document.querySelectorAll('.gym-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===id));if(g&&pan){state.map.flyTo([g.lat,g.lng],Math.max(state.map.getZoom(),15),{duration:.7});state.markers.get(id)?.openPopup()}}
  function toggleFavorite(id){if(state.favorites.has(id))state.favorites.delete(id);else state.favorites.add(id);writeJSON(FAVORITES_KEY,[...state.favorites]);render();toast(state.favorites.has(id)?'انحفظ الجيم على جهازك':'انشال من المحفوظة')}
  function openDirections(id){const g=state.all.find(x=>x.id===id);if(!g)return;window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(g.lat+','+g.lng)}`,'_blank','noopener,noreferrer')}

  function detailHTML(g){const saved=state.favorites.has(g.id);return`<div class="detail-kicker">${g.verified?'مراجع يدويًا':'بيانات OpenStreetMap'}</div><h2 class="detail-title" id="detailsTitle">${esc(g.nameAr||g.name)}</h2>${g.nameAr&&g.nameAr!==g.name?`<p class="detail-address">${esc(g.name)}</p>`:''}<div class="detail-badges"><span>${esc(typeLabel(g.type))}</span><span>${esc(g.area)}</span>${g.women?'<span class="women">للنساء</span>':''}${g.alwaysOpen?'<span>24/7</span>':''}${g.verified?'<span class="verified">✓ متحقق</span>':'<span class="osm">OSM</span>'}</div><div class="detail-info"><div class="info-box"><span>العنوان</span><b>${esc(g.address||g.area)}</b></div><div class="info-box"><span>الدوام</span><b>${esc(g.hours||'غير مذكور')}</b></div><div class="info-box"><span>الهاتف</span><b>${g.phone?`<a href="tel:${esc(g.phone)}">${esc(g.phone)}</a>`:'غير متوفر'}</b></div><div class="info-box"><span>المسافة</span><b>${state.userLocation?esc(distanceLabel(kmBetween(state.userLocation,g))):'فعّل موقعك لحسابها'}</b></div></div>${g.rating?`<div class="info-box"><span>تقييم الدليل</span><b>★ ${g.rating.toFixed(1)}${g.reviews?` · ${g.reviews} مراجعة`:''}</b></div>`:''}<div class="detail-note">${g.approximate?'موضع الدبوس تقريبي ومأخوذ من وصف الموقع؛ استخدم الاتصال أو الاتجاهات للتأكد. ':''}أوقات العمل والأسعار ممكن تتغير؛ تأكد من الجيم قبل الزيارة.</div><div class="detail-actions"><button class="primary" data-detail-directions="${esc(g.id)}">افتح الاتجاهات</button>${g.phone?`<a href="tel:${esc(g.phone)}">اتصل</a>`:''}<button data-detail-save="${esc(g.id)}">${saved?'إلغاء الحفظ':'حفظ'}</button><button data-detail-share="${esc(g.id)}">مشاركة</button></div>`}
  function openDetails(id){const g=state.all.find(x=>x.id===id);if(!g)return;selectGym(id,true);els.detailsContent.innerHTML=detailHTML(g);els.detailsModal.classList.add('open');els.detailsModal.setAttribute('aria-hidden','false')}
  function closeDetails(){els.detailsModal.classList.remove('open');els.detailsModal.setAttribute('aria-hidden','true')}
  function openAbout(){els.aboutModal.classList.add('open');els.aboutModal.setAttribute('aria-hidden','false')}
  function closeAbout(){els.aboutModal.classList.remove('open');els.aboutModal.setAttribute('aria-hidden','true')}
  async function shareGym(id){const g=state.all.find(x=>x.id===id);if(!g)return;const url=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(g.lat+','+g.lng)}`,data={title:g.nameAr||g.name,text:`${g.nameAr||g.name} — ${g.area}`,url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text}\n${url}`);toast('تم نسخ رابط الجيم')}}catch(e){if(e?.name!=='AbortError')toast('ما قدرنا نشارك الرابط')}}

  function showUserMarker(lat,lng){if(state.userMarker)state.map.removeLayer(state.userMarker);const icon=L.divIcon({className:'',html:'<div class="user-dot"><i></i></div>',iconSize:[28,28],iconAnchor:[14,14]});state.userMarker=L.marker([lat,lng],{icon,zIndexOffset:1000}).addTo(state.map).bindPopup('موقعك التقريبي')}
  function locateUser({sort=true}={}){if(!navigator.geolocation){toast('المتصفح ما يدعم تحديد الموقع');return}els.hint.textContent='جاي نحدد موقعك…';navigator.geolocation.getCurrentPosition(pos=>{const{latitude:lat,longitude:lng,accuracy}=pos.coords;state.userLocation={lat,lng,accuracy};showUserMarker(lat,lng);if(sort)state.sort='nearest';updateSortButtons();render();state.map.flyTo([lat,lng],14,{duration:.8});els.hint.textContent=`موقعك محدد · دقة تقريبية ${Math.round(accuracy)} م`;toast('رتبنا الجيمات حسب قربها منك')},err=>{els.hint.textContent='اسحب الخريطة واستكشف بغداد';toast(err.code===1?'فعّل إذن الموقع حتى نرتب الأقرب':'تعذر تحديد موقعك الآن')},{enableHighAccuracy:true,timeout:10000,maximumAge:300000})}
  function updateSortButtons(){els.sortRecommended.classList.toggle('active',state.sort==='recommended');els.sortNearest.classList.toggle('active',state.sort==='nearest')}
  function setFilter(filter){state.filter=filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));render({fitMap:filter!=='all'})}
  function toast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>els.toast.classList.remove('show'),2600)}

  function overpassQuery(){return`[out:json][timeout:25];(nwr["leisure"="fitness_centre"](around:35000,${BAGHDAD.lat},${BAGHDAD.lng});nwr["leisure"="sports_centre"]["sport"~"fitness|bodybuilding|weightlifting|crossfit",i](around:35000,${BAGHDAD.lat},${BAGHDAD.lng});nwr["sport"~"fitness|bodybuilding|weightlifting|crossfit",i](around:35000,${BAGHDAD.lat},${BAGHDAD.lng});nwr["amenity"="gym"](around:35000,${BAGHDAD.lat},${BAGHDAD.lng}););out center tags;`}
  async function fetchWithTimeout(url,options={},ms=15000){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(t)}}
  async function loadLiveData({force=false}={}){const cached=readJSON(CACHE_KEY,null);if(!force&&cached?.data?.length){const parsed=cached.data.map(x=>x).filter(Boolean);state.all=mergeData(parsed);state.liveLoaded=true;render();const age=Date.now()-cached.ts;els.coverage.textContent=`آخر تحميل حي: ${new Date(cached.ts).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}`;if(age<CACHE_TTL){setStatus('ok','قاعدة موثّقة + خريطة حيّة');return}}setStatus('loading','جاري تحديث خريطة بغداد…');els.refresh.classList.add('loading');const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];let lastErr=null;for(const endpoint of endpoints){try{const body=new URLSearchParams({data:overpassQuery()}),res=await fetchWithTimeout(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body},18000);if(!res.ok)throw new Error(`HTTP ${res.status}`);const json=await res.json(),gyms=(json.elements||[]).map(normalizeOSM).filter(Boolean).filter(g=>kmBetween(BAGHDAD,g)<=38).filter(g=>normalizeText(g.name)!=='');if(!gyms.length)throw new Error('empty response');writeJSON(CACHE_KEY,{ts:Date.now(),data:gyms});state.all=mergeData(gyms);state.liveLoaded=true;render();setStatus('ok','قاعدة موثّقة + خريطة حيّة');els.coverage.textContent=`تحديث حي · ${gyms.length} موقع من OSM + ${SEED_GYMS.length} مراجع`;els.refresh.classList.remove('loading');return}catch(e){lastErr=e}}setStatus('offline','القاعدة الموثّقة · تعذر التحديث الحي');els.coverage.textContent='الاتصال بالخريطة الحيّة تعذر؛ اعرضنا القاعدة المحلية';els.refresh.classList.remove('loading');if(!cached?.data?.length)state.all=[...SEED_GYMS];render();console.warn('RASH.IQ Overpass fetch failed',lastErr)}

  function bindEvents(){
    els.search.addEventListener('input',e=>{state.search=e.target.value;els.clearSearch.hidden=!state.search;render()});
    els.clearSearch.addEventListener('click',()=>{state.search='';els.search.value='';els.clearSearch.hidden=true;render();els.search.focus()});
    els.filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b)setFilter(b.dataset.filter)});
    els.reset.addEventListener('click',()=>{state.search='';els.search.value='';els.clearSearch.hidden=true;setFilter('all')});
    els.refresh.addEventListener('click',()=>loadLiveData({force:true}));els.locate.addEventListener('click',()=>locateUser());els.floatingLocate.addEventListener('click',()=>locateUser());
    els.sortRecommended.addEventListener('click',()=>{state.sort='recommended';updateSortButtons();render()});els.sortNearest.addEventListener('click',()=>{if(!state.userLocation){locateUser();return}state.sort='nearest';updateSortButtons();render()});els.sheetToggle.addEventListener('click',()=>els.sidebar.classList.toggle('collapsed'));
    els.gymList.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){e.stopPropagation();toggleFavorite(save.dataset.save);return}const directions=e.target.closest('[data-directions]');if(directions){e.stopPropagation();openDirections(directions.dataset.directions);return}const card=e.target.closest('.gym-card');if(card)openDetails(card.dataset.id)});
    els.gymList.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('gym-card')){e.preventDefault();openDetails(e.target.dataset.id)}});
    document.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]'))closeDetails();if(e.target.closest('[data-close-about]'))closeAbout();const d=e.target.closest('[data-detail-directions]');if(d)openDirections(d.dataset.detailDirections);const s=e.target.closest('[data-detail-save]');if(s){toggleFavorite(s.dataset.detailSave);openDetails(s.dataset.detailSave)}const sh=e.target.closest('[data-detail-share]');if(sh)shareGym(sh.dataset.detailShare)});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetails();closeAbout()}});
    document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));const nav=btn.dataset.nav;if(nav==='map'){els.sidebar.classList.add('collapsed');state.map.invalidateSize()}if(nav==='nearby'){els.sidebar.classList.remove('collapsed');locateUser()}if(nav==='saved'){els.sidebar.classList.remove('collapsed');setFilter('saved')}if(nav==='about')openAbout()}));
    window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;els.install.hidden=false});els.install.addEventListener('click',async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;els.install.hidden=true});window.addEventListener('appinstalled',()=>{els.install.hidden=true;toast('RASH.IQ انثبت على جهازك')});
  }
  function registerSW(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
  function init(){initMap();bindEvents();render();registerSW();setTimeout(()=>state.map.invalidateSize(),120);loadLiveData()}
  init();
})();
